<?
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["kabinet-pokupatelya"]["*"]="D";
$PERM["kabinet-pokupatelya"]["6"]="X";
$PERM["kabinet-prodavtsa"]["*"]="D";
$PERM["kabinet-prodavtsa"]["7"]="X";
$PERM["search"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>