<?
$aMenuLinks = Array(
	Array(
		"Дашборд", 
		"/s2/statistic_na/dashboard/", 
		Array(), 
		Array("menu_ico"=>"grid"), 
		"" 
	),
	Array(
		"Основные", 
		"/s2/statistic_na/main/", 
		Array(), 
		Array("menu_ico"=>"menu-button-wide"), 
		"CSite::InGroup(array(1,10))" 
	),
	Array(
		"Дополнительные", 
		"/s2/statistic_na/extra/", 
		Array(), 
		Array("menu_ico"=>"files"), 
		"CSite::InGroup(array(1,10))" 
	),
	Array(
		"Профиль", 
		"/s2/statistic_na/profile/", 
		Array(), 
		Array("menu_ico"=>"person"), 
		"" 
	)
);
?>